---
- name: Adding {{ item }} to the master list
  set_fact:
    dcos_master_ip: "{{ item }}"
    
- name: Create fragment for host {{ dcos_master_ip }} at {{ dcos_fragments_dir }}/config-3-master-list-entry-{{ dcos_master_ip }}.yml
  template:
    src: config-3-master-list-entry.yml
    dest: "{{ dcos_fragments_dir }}/config-3-master-list-entry-{{ dcos_master_ip }}.yml"
    mode: 0644
