---
- name: Adding {{ item }} to the master list
  set_fact:
    dcos_resolver_ip: "{{ item }}"
    
- name: Create fragment for host {{ dcos_resolver_ip }} at {{ dcos_fragments_dir }}/config-5-resolver-list-entry-{{ dcos_resolver_ip }}.yml
  template:
    src: config-5-resolver-list-entry.yml
    dest: "{{ dcos_fragments_dir }}/config-5-resolver-list-entry-{{ dcos_resolver_ip }}.yml"
    mode: 0644
